# Generated by Django 4.2.3 on 2023-07-17 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('year', models.IntegerField()),
                ('platform', models.CharField(max_length=20)),
                ('type', models.CharField(max_length=10)),
                ('director', models.CharField(blank=True, max_length=100, null=True)),
                ('cast', models.CharField(blank=True, max_length=200, null=True)),
                ('rating', models.CharField(blank=True, max_length=50, null=True)),
                ('duration', models.CharField(blank=True, max_length=50, null=True)),
                ('genre', models.CharField(max_length=400)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
