import numpy as np

# Create a dictionary of acceptable genres
genre_mapping = {
    'Arts, Entertainment, and Culture': 'Arts & Lifestyle',
    'Stand-Up Comedy & Talk Shows': 'Stand-Up',
    'Music Videos and Concerts': 'Musicals',
    'Spanish-Language TV Shows': 'Spanish',
    'Children & Family Movies': 'Children & Family',
    'Game Show / Competition': 'Game Show',
    'Soap Opera / Melodrama': 'Drama',
    'Faith and Spirituality': 'Faith & Spirituality',
    'International TV Shows': 'International',
    'TV Action & Adventure': 'Action & Adventure',
    'Talk Show and Variety': 'Talk Show & Variety',
    'Faith & Spirituality': 'Faith & Spirituality',
    'International Movies': 'International',
    'Science & Technology': 'Science & Nature',
    'Young Adult Audience': 'Teen & Young Adult',
    'Lifestyle & Culture': 'Arts & Lifestyle',
    'Science & Nature TV': 'Science & Nature',
    'TV Sci-Fi & Fantasy': 'Science Fiction & Fantasy',
    'Action & Adventure': 'Action & Adventure',
    'Classic & Cult TV': 'Classic & Cult',
    'Health & Wellness': 'Health & Wellness',
    'Romantic TV Shows': 'Romantic',
    'Action-Adventure': 'Action & Adventure',
    'British TV Shows': 'British',
    'Music & Musicals': 'Musicals',
    'Animals & Nature': 'Science & Nature',
    'Special Interest': 'Science & Nature',
    'Sci-Fi & Fantasy': 'Science Fiction & Fantasy',
    'Show and Variety': 'Talk Show & Variety',
    'Adult Animation': 'Animation',
    'Korean TV Shows': 'Korean',
    'Romantic Movies': 'Romantic',
    'Science Fiction': 'Science Fiction & Fantasy',
    'Stand-Up Comedy': 'Stand-Up',
    'Anime Features': 'Anime',
    'Classic Movies': 'Classic & Cult',
    'Crime TV Shows': 'Crime',
    'Documentaries': 'Documentary',
    'Horror Movies': 'Horror',
    'International': 'International',
    'Sports Movies': 'Sports',
    'Sketch Comedy': 'Stand-Up',
    'Teen TV Shows': 'Teen & Young Adult',
    'Coming of Age': 'Teen & Young Adult',
    'Anime Series': 'Anime',
    'Concert Film': 'Arts & Lifestyle',
    'LGBTQ Movies': 'LGBTQ+',
    'TV Mysteries': 'Mystery',
    'TV Thrillers': 'Thriller',
    'Cult Movies': 'Classic & Cult',
    'TV Comedies': 'Comedy',
    'Documentary': 'Documentary',
    'and Culture': 'Arts & Lifestyle',
    'Docuseries': 'Documentary',
    'Game Shows': 'Game Show',
    'Historical': 'History',
    'Reality TV': 'Reality TV',
    'Unscripted': 'Reality TV',
    'Late Night': 'Talk Show & Variety',
    'Adventure': 'Action & Adventure',
    'Animation': 'Animation',
    'Lifestyle': 'Arts & Lifestyle',
    'TV Dramas': 'Drama',
    'TV Horror': 'Horror',
    'Talk Show': 'Talk Show & Variety',
    'Thrillers': 'Thriller',
    'Survival': 'Action & Adventure',
    'Cartoons': 'Animation',
    "Kids' TV": 'Children & Family',
    'Classics': 'Classic & Cult',
    'Stand Up': 'Stand-Up',
    'Thriller': 'Thriller',
    'Suspense': 'Thriller',
    'Comedies': 'Comedy',
    'Fitness': 'Health & Wellness',
    'History': 'History',
    'Musical': 'Musicals',
    'Mystery': 'Mystery',
    'Reality': 'Reality TV',
    'Romance': 'Romantic',
    'Fantasy': 'Science Fiction & Fantasy',
    'Variety': 'Talk Show & Variety',
    'Action': 'Action & Adventure',
    'Travel': 'Arts & Lifestyle',
    'Family': 'Children & Family',
    'Comedy': 'Comedy',
    'Parody': 'Comedy',
    'Sitcom': 'Comedy',
    'Dramas': 'Drama',
    'Horror': 'Horror',
    'LGBTQ+': 'LGBTQ+',
    'Latino': 'Spanish',
    'Sports': 'Sports',
    'Anime': 'Anime',
    'Dance': 'Arts & Lifestyle',
    'Crime': 'Crime',
    'Drama': 'Drama',
    'LGBTQ': 'LGBTQ+',
    'Music': 'Arts & Lifestyle',
    'Kids': 'Children & Family',
    'Teen': 'Teen & Young Adult',
    'Arts': 'Arts & Lifestyle',
}

# Create a dictionary for ratings null values
rating_mapping = {
    'min': np.nan,
    'nan': np.nan,
    'None': np.nan,
    'NR': np.nan,
    'UR': np.nan,
    'NOT RATED': np.nan,
    'NOT_RATE': np.nan,
    'UNRATED': np.nan,
}
